### PR TITLE
Avoid normalizing image URLs (fixes #215)

### LINKED ISSUE #215: Image url encode problem
Hi,

Thank you your great gem.
Sadly we found an issue when we tried to use this gem.
We're using the latest version of this gem (5.4.1).

We found this issue when we tried to scraping theguardian pages. e.g. https://www.theguardian.com/politics/2017/sep/13/theresa-may-to-deliver-brexit-speech-in-florence but I guess you can reproduce the problem with any pages of theguardian.
metainspector

We need the best match of the images which is coming from the `page.images.best` and we get that image url as we expected, but the url doesn't work.
signatureerror

The problem is coming from the url encoding. For example the `page.meta["og:image"]` gives us this url (which is working):
```
https://i.guim.co.uk/img/media/d63524a252711a991bfc7ebe1d065f221c71ca13/0_147_4209_2525/master/4209.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&crop=faces%2Centropy&bm=normal&ba=bottom%2Cleft&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNS8yNS9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=e13bb69825bcc74d600294893dbef88e
```
but the `page.images.best` gives us this url (which is not working):
```
https://i.guim.co.uk/img/media/d63524a252711a991bfc7ebe1d065f221c71ca13/0_147_4209_2525/master/4209.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&crop=faces,entropy&bm=normal&ba=bottom,left&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNS8yNS9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=e13bb69825bcc74d600294893dbef88e
```
So it's converting `%2C` to `,` and the cache server throw an error.

### PR DESCRIPTION
**Pull request by jschwindt**
Here is my PR for #215. I also ugraded Nokogiri because it had some security issues.

### CODE REVIEW

File: lib/meta_inspector/url.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@ class URL
     attr_reader :url
 
     def initialize(initial_url, options = {})
-      options        = defaults.merge(options)
+      options        = self.class.defaults.merge(options)
```
Comment (jaimeiniesta) [inline lib/meta_inspector/url.rb]: Not sure why this is has been changed here, why the need for `self`?

File: lib/meta_inspector/url.rb [hunk 2]
```diff
@@ -56,19 +56,21 @@ def url=(new_url)
...
+        options[:normalize] ? uri.normalize.to_s : uri.to_s
       end
     rescue MetaInspector::ParserError, Addressable::URI::InvalidURIError, ArgumentError
       nil
     end
 
     private
 
-    def defaults
+    def self.defaults
```
Comment (jaimeiniesta) [inline lib/meta_inspector/url.rb]: Same here from above comment.

File: lib/meta_inspector/url.rb (hunk 1 above)
Comment (jschwindt) [reply lib/meta_inspector/url.rb]: Because I wanted to use the same `default` method in `def self.absolutify(...)` without having to instantiate the URL object or without duplicating code. Maybe there is a better way...

**Comment by jaimeiniesta** [comment]
@jschwindt thanks, this PR looks great, but I cannot merge because there are non-related commits in it - check https://github.com/jaimeiniesta/metainspector/pull/241/commits - I see other commits for best_description, etc.

Could you please create a fresh branch from `master` in the main repo, and include only the changes for the normalizing issue, please?

I'll update the Nokogiri dependency apart.

**Comment by jschwindt** [comment]
Done! Please let me know if you have any other issue while merging it.

**Comment by jaimeiniesta** [comment]
Perfect! Thanks!
